services:
  music-lib:
    build: .
    image: music-lib:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./hls_cache:/app/hls_cache
    environment:
      # Set to "true" for readonly mode (no add/delete tracks)
      - READONLY=false
